---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory  # Staging URL
    server: https://acme-v02.api.letsencrypt.org/directory # Production URL
    email: cloudflare@jakelevirne.com
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
    - dns01:
        cloudflare:
          email: cloudflare@jakelevirne.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
