service:
  type: LoadBalancer

parent:
  claiming:
    enabled: true
    token: YOUR_CLAIM_TOKEN
    rooms: YOUR_ROOM_ID

child:
  claiming:
    enabled: true
    token: YOUR_CLAIM_TOKEN
    rooms: YOUR_ROOM_ID
  configs:
    netdata:
      data: |
        [global]
          memory mode = ram
          history = 3600
        [health]
          enabled = no