---
- name: Ensure Vault password is provided
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check for vault access
      ansible.builtin.debug:
        msg: "Checking vault access (e.g. --ask-vault-pass)"
      vars:
        vault_test: "{{ lookup('ansible.builtin.file', 'secrets.yml') }}"
      failed_when: vault_test is undefined

- name: Configure the dataserver nodes
  hosts: nfs_hosts
  become: yes
  vars_files:
    - secrets.yml
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
