---
- name: Ensure Vault password is provided
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check for vault access
      ansible.builtin.debug:
        msg: "Checking vault access (e.g. --ask-vault-pass)"
      vars:
        vault_test: "{{ lookup('ansible.builtin.file', 'secrets.yml') }}"
      failed_when: vault_test is undefined

- name: Join MicroK8s Nodes into Cluster
  hosts: pi_hosts
  become: yes
  vars_files:
    - secrets.yml  
  tasks:
    - name: Generate MicroK8s join command on the master
      ansible.builtin.command: /snap/bin/microk8s add-node --token-ttl 120
      register: join_command
      when: inventory_hostname == 'pi1.local'
      run_once: true

    - name: Parse the join command
      set_fact:
        microk8s_join_command: "{{ join_command.stdout.split('\n') | select('match', '^microk8s join') | first }}"
      when: inventory_hostname == 'pi1.local'

    - name: Write microk8s join command to a local file for sharing
      ansible.builtin.copy:
        dest: "/tmp/microk8s_join_command.txt"
        content: "{{ microk8s_join_command }}"
        mode: '0644'
      delegate_to: localhost
      become: no
      run_once: true
      when: inventory_hostname == 'pi1.local'

    - name: Read microk8s join command from local file on other nodes
      ansible.builtin.slurp:
        src: "/tmp/microk8s_join_command.txt"
      register: join_cmd_file
      delegate_to: localhost
      become: no
      when: inventory_hostname != 'pi1.local'

    - name: Set microk8s join command fact from file on other nodes
      set_fact:
        microk8s_join_command: "/snap/bin/{{ join_cmd_file['content'] | b64decode }}"
      when: inventory_hostname != 'pi1.local'

    - name: Join to the MicroK8s cluster on other nodes
      ansible.builtin.command: "{{ microk8s_join_command }}"
      when: inventory_hostname != 'pi1.local' and microk8s_join_command is defined

    - name: Reboot all machines to apply changes
      ansible.builtin.reboot:
        msg: "Rebooting after MicroK8s configuration"
        reboot_timeout: 600  # Adjust this timeout as needed
      when: microk8s_join_command is defined
