---
- name: Setup and clone disk using Clonezilla
  hosts: imager_hosts
  become: yes
  tasks:
    - name: Update and upgrade apt packages on imager
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Clonezilla
      ansible.builtin.apt:
        name: clonezilla
        state: present

    - name: Ensure /home/partimag directory exists
      ansible.builtin.file:
        path: /home/partimag
        state: directory

    - name: Install nfs-common for mounting
      ansible.builtin.apt:
        name: nfs-common
        state: present

    - name: Mount OS images directory
      ansible.builtin.mount:
        path: /home/partimag
        src: 192.168.87.2:/srv/os_images
        fstype: nfs
        state: mounted
        opts: defaults

    - name: Unmount /dev/sda1
      ansible.builtin.mount:
        path: /mnt/dev/sda1
        src: /dev/sda1
        fstype: auto
        state: unmounted

    - name: Unmount /dev/sda2
      ansible.builtin.mount:
        path: /mnt/dev/sda2
        src: /dev/sda2
        fstype: auto
        state: unmounted

    - name: Run ocs-sr with auto-confirmation via yes
      ansible.builtin.shell:
        cmd: yes | sudo /usr/sbin/ocs-sr -g auto -e1 auto -e2 -r -j2 -c -k0 -p noreboot -batch -nogui -scr restoredisk pi-img sda
      become: yes


    - name: Ensure /mnt/sda1 directory exists
      ansible.builtin.file:
        path: /mnt/sda1
        state: directory

    - name: Mount /dev/sda1
      ansible.builtin.mount:
        path: /mnt/sda1
        src: /dev/sda1
        fstype: auto
        state: mounted

    - name: Update firstrun.sh to replace changeme with appropriate pi<number>
      ansible.builtin.replace:
        path: /mnt/sda1/firstrun.sh
        regexp: 'changeme'
        replace: "pi{{ (inventory_hostname.split('.') | first) | regex_search('(\\d+)$') }}"

    - name: Disable WiFi by setting dtoverlay in config.txt
      lineinfile:
        path: /mnt/sda1/config.txt
        line: dtoverlay=disable-wifi
        create: no
        state: present

    - name: Unmount /dev/sda1
      ansible.builtin.mount:
        path: /mnt/sda1
        src: /dev/sda1
        fstype: auto
        state: unmounted 

    - name: Schedule a reboot in one minute (fire and forget)
      ansible.builtin.command:
        cmd: shutdown -r +1
      ignore_errors: yes

# TODO: DISABLE WIFI
