---
- name: Test ansible.builtin.shell module
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Update hostname based on host
      ansible.builtin.shell:
        cmd: echo "pi{{ ('imager1.local'.split('.') | first) | regex_search('(\d+)$') }}"
      register: date_output

#    - name: Display the inventory hostname
#      ansible.builtin.shell: "echo pi{{ inventory_hostname }}"
#      register: date_output

    - name: Show output
      ansible.builtin.debug:
        msg: "{{ date_output.stdout }}"
