- name: Rename and ensure line in TEST.txt
  hosts: pi_hosts
  become: yes
  tasks:
    - name: Check if ~/.TEST.txt exists
      ansible.builtin.find:
        paths: "/home/pi"
        patterns: ".TEST.txt"
      register: test_file_result

    - name: Rename ~/.TEST.txt to ~/TEST.txt if it exists
      ansible.builtin.command:
        cmd: mv /home/pi/.TEST.txt /home/pi/TEST.txt
      when: test_file_result.matched == 0

    - name: Ensure line exists in TEST.txt
      ansible.builtin.lineinfile:
        path: "/home/pi/TEST.txt"
        line: "This is the line to append."
        mode: '0644'
        create: yes